name: CI

on:
  push:
    branches: '*'
    tags: v*
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

env:
  MACOSX_DEPLOYMENT_TARGET: 10.9

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test ${{ matrix.data.os.target_triple }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.data.os.host }}
    continue-on-error: ${{ matrix.nightly == 'nightly' }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        data:
          - os:
              host: ubuntu-latest
              target_triple: x86_64-alpine-linux-musl
            docker: true

          - os:
              host: macOS-latest
              target_triple: x86_64-apple-macos10.9

          - os:
              host: windows-latest
              target_triple: x86_64-pc-windows-msvc

          - os:
              target: freebsd
              version: '13.1'
              target_triple: x86_64-unknown-freebsd13.1
              host: ubuntu-latest
            cross_platform_actions: true

        compiler:
          - ldc-latest

        llvm:
          - '15.0.7'

        include:
          - compiler: dmd-latest
            llvm: '15.0.7'
            arch: x86_64
            data:
              os:
                host: windows-latest
                target_triple: x86_64-pc-windows-msvc

          - compiler: dmd-beta
            llvm: '15.0.7'
            arch: x86_64
            data:
              os:
                host: windows-latest
                target_triple: x86_64-pc-windows-msvc

          - compiler: ldc-beta
            llvm: '15.0.7'
            arch: x86_64
            data:
              os:
                host: ubuntu-latest
                target_triple: x86_64-alpine-linux-musl
              docker: true

          - compiler: dmd-master
            llvm: '15.0.7'
            arch: x86_64
            nightly: nightly
            data:
              os:
                host: windows-latest
                target_triple: x86_64-pc-windows-msvc

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: test
        uses: ./.github/workflows/support/build
        with:
          action: test
          arch: ${{ matrix.arch }}
          docker_arch: ${{ matrix.docker_arch }}
          target_operating_system: ${{ matrix.data.os.target }}
          target_version: ${{ matrix.data.os.version }}
          llvm: ${{ matrix.llvm }}
          target_triple: ${{ matrix.data.os.target_triple }}
          cross_platform_actions: ${{ matrix.data.cross_platform_actions }}
          docker: ${{ matrix.data.docker }}
          compiler: ${{ matrix.compiler }}
